### ISSUE TITLE
[Feature request] "respond with X to delete the message"

### ISSUE THREAD

**Issue by crckdns** [Kilvoctu/aiyabot#13]
It would be really great to have an ability to order the bot to delete a created image from the chat.
very important in cases when the created image has explicit content not allowed by TOS of discord.

Just a simple "note" when the bot is posting an image with the hint "react with X to delete created picture" 
and under it the wanted reaction a user can click.
Have seen it working perfectly on another bot.

Like that:

![reactwithXtodelete](https://user-images.githubusercontent.com/787954/198066537-1a1cee48-9c20-4179-b60b-521c219a67f5.JPG)

**Comment by Kilvoctu** [comment]
Hi, this feature already exists, and it should be working if you react with ❌.
I just didn't like that message after every generation, so I tucked it away in /tips.

The bot is supposed to add an ❌ reaction on its own; I didn't notice it wasn't since on my server mine doesn't have "Add Reactions" permission. I'll look into why it's not doing it.

If you want to add in the reminder text on each generation just add this line of code: 
`embed.add_field(name='delete', value='React with ❌ to delete your own generation')`
right after this line in stablecog.py https://github.com/Kilvoctu/aiyabot/blob/bb7790bf454ab3484074419254323cdd0b60384e/core/stablecog.py#L245

The other bot you referenced is harubaru's bot, which is my favorite and why I got into Stable Diffusion to begin with. This bot is forked off of his 😄

**Comment by Kilvoctu** [comment]
I pushed an update, so bot should add the ❌ reaction after each generation now. It was a simple thing I overlooked 😅
Make sure it has the Add Reactions permission

**Comment by crckdns** [comment]
Thanks a lot for the quick response!

not sure if related but now it's throwing an error instead of generating an image 😕 
`Request -- Cracky#5800 -- Prompt: test
/draw prompt:test negative_prompt: steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:3340029543
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\core\stablecog.py", line 231, in dream
    for i in response['images']:
KeyError: 'images'`

**Comment by Kilvoctu** [comment]
This KeyError keeps haunting me. I've had a lot of trouble fixing it for good because I can't recreate the issue, no matter what I do. 🤔 That key should definitely exist in the response from the Web UI.
Not sure why it would suddenly error out; I only changed an unrelated text string.

Are you running bot through localhost or through gradio-share? Anything else you can share to help me recreate the problem? OS, python version, etc.

**Comment by crckdns** [comment]
sure,
running locally, also the webui is run with --listen on local URL:  http://0.0.0.0:7860

windows 10, 
python 3.10.7
path is E:\!stablediffusion\aiyabot\core\stablecog.py

git hard reseted, so fresh from github.
I doubt those infos will help :/

**Comment by Kilvoctu** [comment]
Our setups are pretty similar.
Hm, I think I may have another idea at why this issue is happening. In your .env file, what do you have for `URL =`? Is it blank or do you have it set to something?

**Comment by Kilvoctu** [comment]
Sorry for all the questions. Did you get the error immediately after /draw or does it generate the image first, then error?

**Comment by crckdns** [comment]
don't worry about the questions, it is for the sake of fixing an error!
it does not generate an image, nor the webui console get's a prompt transfered to generate anything
basically it fails in the save local copy of image for loop according to the errormessage

**Comment by crckdns** [comment]
did some print debugging to get a trace

![printdebug01](https://user-images.githubusercontent.com/787954/198141746-1179a6b6-7f32-4b72-83af-92418a725404.JPG)
`Request -- Cracky#5800 -- Prompt: test
/draw prompt:test negative_prompt: steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:1551445225
debug line 212
debug line 225
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\core\stablecog.py", line 235, in dream
    for i in response['images']:
KeyError: 'images'`

**Comment by Kilvoctu** [comment]
What the situation is telling me is for some reason the bot is not receiving the webui response, or something is wonky with how it's formatted. 🤔

Can you try deleting the whole block of code below `#save local copy of image` https://github.com/Kilvoctu/aiyabot/blob/fdc362053d55a26b454fd7bed40d663ac4fde510/core/stablecog.py#L231-L236
and run it again?
In this scenario it should at least post to Discord, just not save an image. If that happens, I can try to figure out why bot is not reading the webui response.

**Comment by crckdns** [comment]
after deleting the block:

> Request -- Cracky#5800 -- Prompt: test
> /draw prompt:test negative_prompt: steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:2969231770
> debug line 212
> debug line 225
> Traceback (most recent call last):
>   File "E:\!stablediffusion\aiyabot\core\stablecog.py", line 239, in dream
>     image.save(buffer, 'PNG')
> UnboundLocalError: local variable 'image' referenced before assignment

**Comment by crckdns** [comment]
ok interesting, now I undeleted the block and tried again:

> Request -- Cracky#5800 -- Prompt: a white cat
/draw prompt:a white cat negative_prompt: steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:3152597090
debug line 212
debug line 225
debug line 236
debug line 241
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\core\stablecog.py", line 242, in dream
    image.save(f'{DIR}\{epoch_time}-{queue_object.seed}-{queue_object.prompt[0:120]}.png', pnginfo=metadata)
  File "E:\!stablediffusion\aiyabot\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'None\\1666820552-3152597090-a white cat.png'

**Comment by Kilvoctu** [comment]
That particular error tells me it can't find the filepath `None`. It's trying to save the image to folder named "None".
In your .env you can set `DIR = ` to blank or outputs. This is how mine is set up personally
![image](https://user-images.githubusercontent.com/2993060/198145859-da633763-4ece-40d1-8bbd-83181190f6f5.png)

**Comment by Kilvoctu** [comment]
Right above where code saves local copy can you put this `print(response)` and tell me what it prints out? 🤔
Here is fine
![image](https://user-images.githubusercontent.com/2993060/198147018-36ff2e13-92c8-44e0-aee4-916dc3d3448b.png)

**Comment by crckdns** [comment]
uh, after setting the DIR = to blank it did post an image to discord and saved the image to outputs in aiyabot folder
print(response) leads to following:

> R4CGoP3C57GhQDV6Y64qdVFXAhTC29C9V/ohMAABsl1fUA+EC/ujPW6StNL7US6Pnx17LJZ8pCVDjnX0BrkyJ/RNeKJh6dqy0qPez7oP+4U0hFxTGLuXl3NczUiG9H4A3dn8jXH5cEIBRewllPeCyyFrTYZ0WsNsXL8kXbE/0y5FbXqtIFVy+oCkm7NpqvoIfLrFXUFMFwFKvjE0IqIZbMVkUESbS9UaIRRzbMum6mZkBOTinVobknTCAEBO8GFERjOPYt9j1bfC+66PMxZGMRahxi2RZRBjAYXEOUSJ4ZEyF5pHTkHDm5TynBOOS80mwFM5MjIRuSeydA+WWcwYAT7ZSx/kWAUtJufCSc2iaJZUQSIEqyVo5Us6CpRSFVFHSUhxmCsJcZAFHdPXq9vHzHYikpCQNF4GubVVHnUXGYQmBANgFn1OeTlMMHsk7ZxVFWQQcFYaUS0nMTgoDEfiAw/PSrdrMIMx5mQlRPHnEPCwsSFiQMY+l7ZsyDcuck5DzWMT7xolw5oJETXDTvNx8+frp/qHfdOMw7g+r57sHgrzfrNbv3vRt9/j4+Pi4HG6unh4eh9MADk/n/OaLq+fzlM9LyoCUpoSrfv3/AbP6bkXfwYS2AAAAAElFTkSuQmCC'], 'parameters': {'enable_hr': False, 'denoising_strength': None, 'firstphase_width': 0, 'firstphase_height': 0, 'prompt': 'a yellow cat', 'styles': None, 'seed': 2731297908, 'subseed': -1, 'subseed_strength': 0, 'seed_resize_from_h': 0, 'seed_resize_from_w': 0, 'batch_size': 1, 'n_iter': 1, 'steps': 30, 'cfg_scale': 7.0, 'width': 512, 'height': 512, 'restore_faces': False, 'tiling': False, 'negative_prompt': '', 'eta': None, 's_churn': 0.0, 's_tmax': None, 's_tmin': 0.0, 's_noise': 1.0, 'override_settings': None, 'sampler_index': 'Euler a'}, 'info': {'prompt': 'a yellow cat', 'all_prompts': ['a yellow cat'], 'negative_prompt': '', 'seed': 2731297908, 'all_seeds': [2731297908], 'subseed': 2453759697, 'all_subseeds': [2453759697], 'subseed_strength': 0, 'width': 512, 'height': 512, 'sampler_index': 0, 'sampler': 'Euler a', 'cfg_scale': 7.0, 'steps': 30, 'batch_size': 1, 'restore_faces': False, 'face_restoration_model': None, 'sd_model_hash': '7460a6fa', 'seed_resize_from_w': 0, 'seed_resize_from_h': 0, 'denoising_strength': None, 'extra_generation_params': {}, 'index_of_first_image': 0, 'infotexts': ['a yellow cat\nSteps: 30, Sampler: Euler a, CFG scale: 7.0, Seed: 2731297908, Size: 512x512, Model hash: 7460a6fa'], 'styles': [], 'job_timestamp': '20221026234558', 'clip_skip': 1}}
debug line 236
debug line 241
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\venv\lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "E:\!stablediffusion\aiyabot\aiya.py", line 74, in on_raw_reaction_add
    message = await self.get_channel(ctx.channel_id).fetch_message(ctx.message_id)
AttributeError: 'NoneType' object has no attribute 'fetch_message'

**Comment by crckdns** [comment]
and when clicking on the X it throws:

> Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\venv\lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "E:\!stablediffusion\aiyabot\aiya.py", line 74, in on_raw_reaction_add
    message = await self.get_channel(ctx.channel_id).fetch_message(ctx.message_id)
AttributeError: 'NoneType' object has no attribute 'fetch_message'

**Comment by crckdns** [comment]
yeah, the only output now in console is basically the prompt and the error above (ignore the debug lines)

> Request -- Cracky#5800 -- Prompt: a green cat
/draw prompt:a green cat negative_prompt: steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:4191768576
debug line 212
debug line 225
debug line 236
debug line 241
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "E:\!stablediffusion\aiyabot\venv\lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "E:\!stablediffusion\aiyabot\aiya.py", line 74, in on_raw_reaction_add
    message = await self.get_channel(ctx.channel_id).fetch_message(ctx.message_id)
AttributeError: 'NoneType' object has no attribute 'fetch_message'

DIR is now set to output folder of my webui, so it doesn't land in different locations

> DIR = 'E:\!stablediffusion\stable-diffusion-webui\outputs\txt2img-images'

thanks for guiding me in right direction! 
deleting works now!

**Comment by Kilvoctu** [comment]
No problem, thanks for working with me 👍👍 I have no python experience prior to this bot, so there are a lot of obvious amateur mistakes I'm making while I learn 😅

Yeah that's where I set my DIR too, lol, and is why I wanted user to be able to set the location.
