### ISSUE TITLE
On fresh install default DIR crashes

### ISSUE THREAD

**Issue by Pyrotuna** [Kilvoctu/aiyabot#15]
I'm tired af at the moment so I'm not debugging it right now but here it is:

```
Traceback (most recent call last):
  File "D:\githu\aiyabot-main\aiya.py", line 24, in <module>
    self.load_extension('core.stablecog')
  File "D:\githu\aiyabot-main\venv\lib\site-packages\discord\cog.py", line 893, in load_extension
    self._load_from_module_spec(spec, name)
  File "D:\githu\aiyabot-main\venv\lib\site-packages\discord\cog.py", line 760, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'core.stablecog' raised an error: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

it is solved by setting .env DIR = outputs

**Comment by Kilvoctu** [comment]
Haha, I feel that. I've been learning Python and debugging this bot nearly nonstop for almost a week.

It's working for me on my main machine with a blank DIR = . I'll check my other machine and look into it. Probably I need to do the DIR check in the main aiya file not stablecog..
![image](https://user-images.githubusercontent.com/2993060/198187276-59ed97bf-4250-4845-8185-ce0ebe9bd5b2.png)

**Comment by Pyrotuna** [comment]
btw, just so we're not working on the same thing (hopefully lol), I'm trying to set changeable defaults for the bot so things like steps, negative prompts and sampler can be preset without inputting them each time

**Comment by Kilvoctu** [comment]
Not sure what you mean, but the defaults are currently initialized here in stablecog.py
![image](https://user-images.githubusercontent.com/2993060/198188975-20069ecd-701e-4d6f-8f5b-72cd5d96d329.png)
These values pass thru when the user doesn't set anything. I won't be touching this code.

**Comment by Kilvoctu** [comment]
> it is solved by setting .env DIR = outputs

You are making sure to at least have `DIR = `? Even if it's blank, the environment variable has to exist. For example, this is mine:
![image](https://user-images.githubusercontent.com/2993060/198189742-c6d22f18-27c5-4478-99a3-2cdb5955ccf1.png)
I got the TypeError if my .env didn't contain `DIR = ` at all

**Comment by Pyrotuna** [comment]
ohhh that's probably it, I just copied my old .env after updating and it didn't have DIR at all

**Comment by Kilvoctu** [comment]
Not a problem now. I pushed an update so people don't even have to set URL and DIR if they don't want to.
