### ISSUE TITLE
 Invalid URL '/login': No scheme supplied.

### ISSUE THREAD

**Issue by cyberofficial** [Kilvoctu/aiyabot#16]
```python
Traceback (most recent call last):
  File "Y:\stablediff\aiyabot_test\subtest\core\stablecog.py", line 231, in dream
    s.post(URL + '/login', data=login_payload)
  File "Y:\stablediff\aiyabot_test\subtest\pydata\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "Y:\stablediff\aiyabot_test\subtest\pydata\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "Y:\stablediff\aiyabot_test\subtest\pydata\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "Y:\stablediff\aiyabot_test\subtest\pydata\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "Y:\stablediff\aiyabot_test\subtest\pydata\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/login': No scheme supplied. Perhaps you meant http:///login?
```

**Comment by Kilvoctu** [comment]
I updated how the .env file is loaded with 5daec7016239653a36c67da5c46bce4a13a16464.
You only need to add `URL =` if you're not using the default http://127.0.0.1:7860. So if it's already in there and is set to blank, you can delete that line.
The readme was updated with how .env should look. Basically only TOKEN required with optional additional variables if people aren't using the defaults.

**Comment by cyberofficial** [comment]
my env is correct 
![image](https://user-images.githubusercontent.com/19499442/198403506-0db4b652-ebc9-40e2-9a8d-518cc26b3e66.png)

after a while of toying around, had to revert some code where `is not None` was present like this section.: 
 https://github.com/Kilvoctu/aiyabot/commit/5daec7016239653a36c67da5c46bce4a13a16464#diff-b4e4fe2a2251f2874dd130464927ae19d3015b0f8570fbd59bb75dfe7bbf428dL35-L40 

this was like that for anaconda environments handling, since it's universal across all python versions and operating systems and code books, `is not None` is semi restricted across platforms environment handling in .env installs

**Comment by Kilvoctu** [comment]
Are you saying `== ''` achieves the same thing as `is not None` *and* works in all environments? I'll update it if it fixes everything.
Sorry, I'm not a programmer and got no python experience prior to starting this bot project. I'm just some newbie on Windows

**Comment by cyberofficial** [comment]
Pretty much,

There’s a some differences between the two Python identity operators `is` & `==`. Your code can run okay, But Python `is` operator is to compare numbers and values of using None types, until it suddenly doesn’t. You might have read somewhere that the Python `is` operator is better to use than the `==` operator;. However, it’s crucial to keep in mind that these operators don’t behave quite the same.

The `==` operator compares the value or equality of two objects, whereas the Python `is` operator checks whether two variables point to the same object in memory. In the cases of your bot, this means you should use the equality operators `==` and `!=` not user `is` unless you strictly comparing stuff in memory.

I've learnt the hard way and had to rewrite tons of code because suddenly a piece of code that used `is` decided to stop working in a different python environment. It's fine when using regular python and python -m env, but in many use cases, anaconda (conda) python and stuff like google's codeblock python code handling will toss an error because you are not using valid methods.

So, when comparing with a literal, always use == 

Example case


```python
# == and is operator 
# [] is an empty list 
list1 = [] 
list2 = [] 
list3=list1 
  
if (list1 == list2): 
   print("True") 
else: 
   print("False") 
  
if (list1 is list2): 
   print("True") 
else: 
   print("False") 
  
if (list1 is list3): 
   print("True") 
else:     
   print("False")
```

Output
```
True
False
True
```

**Comment by Kilvoctu** [comment]
Thanks for the explanation and example! I'll need to be careful with what changes I make, or if changes are even needed.
Most of my experience is stumbling around and looking at questions from stackoverflow, and not too much good fundamentals.
