### ISSUE TITLE
txt2img failed when using /draw

### ISSUE THREAD

**Issue by RSAStudioGames** [Kilvoctu/aiyabot#165]
**Describe the bug**  
When I use `/draw` command in Discord to generate an image, it immediately gives me the error "`txt2img failed An invalid parameter was found! 'images'`". I have tried using different prompts, models, and other arguments, but the error remains the same.

The other commands work as usual from what I've tested. Upscaling works without issues either.

---

**Environment**
 - OS: Linux - Ubuntu 22.04.1 LTS

I currently have two Ubuntu VMs. One is hosting Aiyabot and the other is hosting Stable Diffusion.
Aiyabot has no issues using the API and seems to be correctly, for the most part, configured.

---

**Console logs**  
Aiyabot console log when sending /draw request:
`Request -- Username#1111 -- Prompt: test -- Using model:`

Stable Diffusion console log after sending API request from bot:
```
API error: POST: http://172.16.0.12:7860/sdapi/v1/txt2img {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': "There is no current event loop in thread 'AnyIO worker thread'."}
Traceback (most recent call last):
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rsa/stable-diffusion-webui/modules/api/api.py", line 145, in exception_handling
    return await call_next(request)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/rsa/stable-diffusion-webui/modules/api/api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/rsa/stable-diffusion-webui/modules/api/api.py", line 284, in text2imgapi
    self.default_script_arg_txt2img = self.init_default_script_args(script_runner)
  File "/home/rsa/stable-diffusion-webui/modules/api/api.py", line 254, in init_default_script_args
    script_args[script.args_from:script.args_to] = ui_default_values
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1160, in __exit__
    self.app = routes.App.create_app(self)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/routes.py", line 143, in create_app
    app = App(default_response_class=ORJSONResponse)
  File "/home/rsa/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/routes.py", line 113, in __init__
    self.lock = asyncio.Lock()
  File "/usr/lib/python3.8/asyncio/locks.py", line 164, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.
```

**Comment by Kilvoctu** [comment]
Heya, I looked into this a bit and it seems like some issue with the Web UI's API on Linux. This is the bug report I found on the Web UI repo. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9046.  

Someone made a PR that supposedly will resolve it: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9319  
Try adding this PR into your Web UI install and see if it works for you

**Comment by RSAStudioGames** [comment]
Thanks for the tip!

I'm new to working with GitHub, would you mind helping me out with how to add the PR to my WebUI in linux?

**Comment by RSAStudioGames** [comment]
And I hit the wrong button just to drive the point home...

**Comment by Kilvoctu** [comment]
I'm a dumb Windows user, so I do everything with GUI apps lol (Github Desktop).  
This is what I found online about how to do it in CLI: https://devopscube.com/checkout-git-pull-request/ . What it seems to be doing is creating a new branch locally on your machine containing the PR changes 🤔, then swapping to that branch.
The PR in question 9319.

**Comment by RSAStudioGames** [comment]
It works! Thank you!

**Comment by Kilvoctu** [comment]
Glad to hear it 👍👍👍  
If there's anything else, you can log a report or use Discussions. Unfortunately due to circumstances, my development on aiyabot is very slow these days, but I read everything in repo

**Comment by simplesisu** [comment]
Sorry for noob question, but how does one apply the PR change to docker container in unraid? 
_(both SD A1111 and aiyabot runs on unraid)_

**Comment by simplesisu** [comment]
in PR fix there is webui.py file but that doesnt exist here.
