### ISSUE TITLE
queue error in google colab

### ISSUE THREAD

**Issue by maecry** [Kilvoctu/aiyabot#166]
**Describe the bug**  
A clear and concise description of what the bug is. Please keep each bug report limited to one issue.
I tried to run this on google Colab and keep getting this error
current version of python using in Colab is Python 3.9.16
---

**Environment**
 - OS: [e.g. Windows / Linux]
Windows ( Google Colab )
---

**Console logs**  
Put any error messages that show in the console log.
Traceback (most recent call last):
  File "/content/aiyabot/aiya.py", line 5, in <module>
    from core import ctxmenuhandler
  File "/content/aiyabot/core/ctxmenuhandler.py", line 7, in <module>
    from core import settings
  File "/content/aiyabot/core/settings.py", line 11, in <module>
    from core import queuehandler
  File "/content/aiyabot/core/queuehandler.py", line 72, in <module>
    class GlobalQueue:
  File "/content/aiyabot/core/queuehandler.py", line 75, in GlobalQueue
    queue: list[DrawObject | UpscaleObject | IdentifyObject] = []
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Kilvoctu** [comment]
Heya, AIYA requires at minimum python 3.10.  
I really want to bump it down, but that line of code mentioned in the console log there is the sole reason it needs to be 3.10. It also is the key thing that makes the queuing system work 😅

**Comment by maecry** [comment]
oh ok, i will update the colab python and try again, many thanks

**Comment by maecry** [comment]
Hi, sorry for reopening but I still having issue with it on google colab
Configuration file missing! I'm creating config.toml in resources/.
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/aiya.py", line 19, in <module>
    settings.startup_check()
  File "/content/stable-diffusion-webui/core/settings.py", line 384, in startup_check
    config['apiuser'] = os.getenv("APIUSER")
  File "/usr/local/lib/python3.10/site-packages/tomlkit/container.py", line 667, in __setitem__
    self._replace(old_key, key, value)
  File "/usr/local/lib/python3.10/site-packages/tomlkit/container.py", line 688, in _replace
    self._replace_at(idx, new_key, value)
  File "/usr/local/lib/python3.10/site-packages/tomlkit/container.py", line 693, in _replace_at
    value = _item(value)
  File "/usr/local/lib/python3.10/site-packages/tomlkit/items.py", line 243, in item
    raise ValueError(f"Invalid type {type(value)}")
ValueError: Invalid type <class 'NoneType'>
running on Python 3.10.6 using this https://colab.research.google.com/drive/1RNvnsXqMYcNUZw-ammHgW5trHbIdhFs2

**Comment by Kilvoctu** [comment]
On first launch, AIYA creates the config.toml and pulls relevant data from the .env into the config.toml.  
She is erroring out because the .env file doesn't have APIUSER field. I pushed an update so that she will ignore any missing fields in .env when creating the config.toml. Please pull the update and try it out.

**Comment by maecry** [comment]
Thanks It's working fine now, also if any1 need the working colab version for this https://github.com/maecry/stable_diffusion_webui_and_discord_bot

**Comment by Kilvoctu** [comment]
Cool, I'll add it to the wiki (https://github.com/Kilvoctu/aiyabot/wiki/Online-services#user-made-colabs) so people can find it, thanks 👍
