### ISSUE TITLE
Magic prompt error

### ISSUE THREAD

**Issue by wilburforce666** [Kilvoctu/aiyabot#192]
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.10/site-packages/discord/cog.py", line 786, in _load_from_module_spec
    setup(self)
  File "/home/test/aiyabot/core/generatecog.py", line 76, in setup
    bot.add_cog(GenerateCog(bot))
  File "/home/test/aiyabot/core/generatecog.py", line 19, in __init__
    tokenizer = GPT2Tokenizer.from_pretrained(self.model_path)
  File "/home/test/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1760, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/test/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/test/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/test/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'core/MagicPrompt-SD/'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/aiyabot/aiya.py", line 29, in <module>
    self.load_extension('core.generatecog')
  File "/home/test/.local/lib/python3.10/site-packages/discord/cog.py", line 910, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/test/.local/lib/python3.10/site-packages/discord/cog.py", line 791, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'core.generatecog' raised an error: HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'core/MagicPrompt-SD/'. Use `repo_type` argument if needed

So I'm having this issue. I'm on linux ubuntu. older commits work fine.

**Comment by Kilvoctu** [comment]
Heya, seems like an issue following the feature update from PR #184. It's supposed to grab needed files for the /generate command, but seems like something prevented it from doing so. If you follow these steps, does it work https://github.com/Kilvoctu/aiyabot/wiki/Configuration#files-for-generate

Unfortunately I don't have the time currently to troubleshoot this in-depth, but I'll take a more thorough look whenever I can.

**Comment by solareon** [comment]
@wilburforce666 if you can go into the directory where you have installed Aiyabot and run the following commands does this generate any error messages?

```bash
source ./venv/bin/activate
python core/setup_generate.py
```

If so please paste them here so that I can help further troubleshoot.

**Comment by rodti** [comment]
> @wilburforce666 if you can go into the directory where you have installed Aiyabot and run the following commands does this generate any error messages?
> 
> ```shell
> source ./venv/bin/activate
> python core/setup_generate.py
> ```
> 
> If so please paste them here so that I can help further troubleshoot.

I had the same issue, running this command and then running the bot again worked fine.

**Comment by Kilvoctu** [comment]
Please try the above steps if you're still affected. Closing this issue as stale
