### ISSUE TITLE
Comand registration

### ISSUE THREAD

**Issue by amuhak** [Kilvoctu/aiyabot#216]
**Describe the bug**  
I can't get Comand registration to work. I can see the the discord bot is active/connected but it doesn't seem to register its commands preventing anyone from using it. 

p.s. I have given it the perms mentioned [here](https://github.com/Kilvoctu/aiyabot/issues/182)

Thanks in advance for any help!

---

**Environment**
 - OS: Windows 11 22h2

---

**Console logs**  
Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\amuly\Documents\Programs\StableDiffusion\aiyabot\venv\Lib\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\amuly\Documents\Programs\StableDiffusion\aiyabot\venv\Lib\site-packages\discord\bot.py", line 1164, in on_connect
    await self.sync_commands()
  File "C:\Users\amuly\Documents\Programs\StableDiffusion\aiyabot\venv\Lib\site-packages\discord\bot.py", line 719, in sync_commands
    registered_commands = await self.register_commands(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amuly\Documents\Programs\StableDiffusion\aiyabot\venv\Lib\site-packages\discord\bot.py", line 599, in register_commands
    registered = await register("bulk", data, _log=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amuly\Documents\Programs\StableDiffusion\aiyabot\venv\Lib\site-packages\discord\http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 0.options.8.choices: Must be 25 or fewer in length.
In 1.options.7.choices: Must be 25 or fewer in length.
[2023-09-10 21:44:18] INFO: Logged in as

**Comment by solareon** [comment]
This is related to #212. You might be able to apply the fix in that issue as a short term patch or downgrade A1111 below 1.6.0.
