### ISSUE TITLE
"txt2img failed: Connection aborted, Remote end closed connection without response

### ISSUE THREAD

**Issue by Gecktendo** [Kilvoctu/aiyabot#226]
**Describe the bug**  
Running into an issue where about 1 in every 5 image submissions straight up fail. For some reason the connection aborts even though I can tell my gpu put in the work to generate the image.

---

**Environment**
 - OS: Windows 11

---

**Console logs**  
Traceback (most recent call last):
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git Program Files\aiyabot\core\stablecog.py", line 432, in dream
    response = s.post(url=f'{settings.global_var.url}/sdapi/v1/txt2img', json=payload)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Git Program Files\aiyabot\venv\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by wizz13150** [comment]
Aren't you just overloading your VRAM, causing a freeze of the webui on a weak machine ?! 🤔

**Comment by JoshBaldwin101** [comment]
Your log seems to indicate an issue with your Automatic 111 webui and not with aiyabot. What kind of hardware are you running and what parameters are you generating with (i.e, resolution, model, batch size)?
