### ISSUE TITLE
Won't run on Windows 11

### ISSUE THREAD

**Issue by MrJackSpade** [Kilvoctu/aiyabot#255]
---

**Environment**
 - Windows 11

---

```
Z:\aiyabot>launch.bat

Z:\aiyabot>python3.10 -m venv venv

Z:\aiyabot>venv\Scripts\pip.exe install -r requirements.txt
Requirement already satisfied: py-cord in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: python-dotenv in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: requests in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: Pillow in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 4)) (10.2.0)
Requirement already satisfied: tomlkit in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.12.4)
Requirement already satisfied: urlextract in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 6)) (1.9.0)
Requirement already satisfied: transformers in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 7)) (4.38.2)
Requirement already satisfied: torch in z:\aiyabot\venv\lib\site-packages (from -r requirements.txt (line 8)) (2.2.1)
Requirement already satisfied: aiohttp<4.0,>=3.6.0 in z:\aiyabot\venv\lib\site-packages (from py-cord->-r requirements.txt (line 1)) (3.9.3)
Requirement already satisfied: typing-extensions<5,>=4 in z:\aiyabot\venv\lib\site-packages (from py-cord->-r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in z:\aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in z:\aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in z:\aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in z:\aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2024.2.2)
Requirement already satisfied: uritools in z:\aiyabot\venv\lib\site-packages (from urlextract->-r requirements.txt (line 6)) (4.0.2)
Requirement already satisfied: filelock in z:\aiyabot\venv\lib\site-packages (from urlextract->-r requirements.txt (line 6)) (3.13.1)
Requirement already satisfied: platformdirs in z:\aiyabot\venv\lib\site-packages (from urlextract->-r requirements.txt (line 6)) (4.2.0)
Requirement already satisfied: numpy>=1.17 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (1.26.4)
Requirement already satisfied: tokenizers<0.19,>=0.14 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (0.15.2)
Requirement already satisfied: pyyaml>=5.1 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (2023.12.25)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (0.21.4)
Requirement already satisfied: safetensors>=0.4.1 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (0.4.2)
Requirement already satisfied: tqdm>=4.27 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (4.66.2)
Requirement already satisfied: packaging>=20.0 in z:\aiyabot\venv\lib\site-packages (from transformers->-r requirements.txt (line 7)) (23.2)
Requirement already satisfied: fsspec in z:\aiyabot\venv\lib\site-packages (from torch->-r requirements.txt (line 8)) (2024.2.0)
Requirement already satisfied: networkx in z:\aiyabot\venv\lib\site-packages (from torch->-r requirements.txt (line 8)) (3.2.1)
Requirement already satisfied: jinja2 in z:\aiyabot\venv\lib\site-packages (from torch->-r requirements.txt (line 8)) (3.1.3)
Requirement already satisfied: sympy in z:\aiyabot\venv\lib\site-packages (from torch->-r requirements.txt (line 8)) (1.12)
Requirement already satisfied: yarl<2.0,>=1.0 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.9.4)
Requirement already satisfied: attrs>=17.3.0 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (6.0.5)
Requirement already satisfied: aiosignal>=1.1.2 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in z:\aiyabot\venv\lib\site-packages (from aiohttp<4.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (4.0.3)
Requirement already satisfied: colorama in z:\aiyabot\venv\lib\site-packages (from tqdm>=4.27->transformers->-r requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in z:\aiyabot\venv\lib\site-packages (from jinja2->torch->-r requirements.txt (line 8)) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in z:\aiyabot\venv\lib\site-packages (from sympy->torch->-r requirements.txt (line 8)) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: Z:\aiyabot\venv\Scripts\python.exe -m pip install --upgrade pip

Z:\aiyabot>venv\Scripts\python.exe core/setup_generate.py
Missing file for /generate. Downloading merges.txt
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\aiyabot\core\setup_generate.py", line 15, in <module>
    urllib.request.urlretrieve(base_url + file, filepath)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

Z:\aiyabot>venv\Scripts\python.exe aiya.py
Using URL: http://127.0.0.1:7860
Using outputs directory: outputs
/generate command is ENABLED due to USE_GENERATE=True
Traceback (most recent call last):
  File "Z:\aiyabot\venv\lib\site-packages\discord\cog.py", line 790, in _load_from_module_spec
    setup(self)
  File "Z:\aiyabot\core\generatecog.py", line 76, in setup
    bot.add_cog(GenerateCog(bot))
  File "Z:\aiyabot\core\generatecog.py", line 19, in __init__
    tokenizer = GPT2Tokenizer.from_pretrained(self.model_path)
  File "Z:\aiyabot\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2032, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'core/MagicPrompt-SD/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'core/MagicPrompt-SD/' is the correct path to a directory containing all relevant files for a GPT2Tokenizer tokenizer.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\aiyabot\aiya.py", line 35, in <module>
    self.load_extension('core.generatecog')
  File "Z:\aiyabot\venv\lib\site-packages\discord\cog.py", line 912, in load_extension
    self._load_from_module_spec(spec, name)
  File "Z:\aiyabot\venv\lib\site-packages\discord\cog.py", line 795, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'core.generatecog' raised an error: OSError: Can't load tokenizer for 'core/MagicPrompt-SD/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'core/MagicPrompt-SD/' is the correct path to a directory containing all relevant files for a GPT2Tokenizer tokenizer.
```

**Comment by Kilvoctu** [comment]
Heya, I run the aiyabot on a Windows 11 environment.  

The console log says it's not able to load Magic Prompt for some reason, used for the /generate command. You can add the files manually from this repo: https://huggingface.co/Gustavosta/MagicPrompt-Stable-Diffusion/tree/main

Then add these 4 files from there to your aiyabot folder, according to this folder structure
```
 -aiyabot
  '-core
   '-magicprompt-sd
      _
  ->  | config.json
add   | merges.txt
these | pytorch_model.bin
file  | vocab.json
```

Alternatively, if you're not interested in /generate, you can add `USE_GENERATE=False` to your .env file to disable it, bypassing this check.

**Comment by MrJackSpade** [comment]
This did resolve the issue. I have no idea whats going on with HF or why I cant seem to download anything from it lately
