### ISSUE TITLE
Unable to refresh settings

### ISSUE THREAD

**Issue by wilburforce666** [Kilvoctu/aiyabot#266]
**Describe the bug**  
Upon running refresh settings command I get error The application did not respond

---

**Environment**
 - OS: Ubuntu 22

---

**Console logs**  
2|aiya     |     await coro
2|aiya     |   File "/usr/local/lib/python3.10/dist-packages/discord/webhook/async_.py", line 220, in request
2|aiya     |     raise NotFound(response, data)
2|aiya     | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
2|aiya     | 
2|aiya     | The above exception was the direct cause of the following exception:
2|aiya     | 
2|aiya     | Traceback (most recent call last):
2|aiya     |   File "/usr/local/lib/python3.10/dist-packages/discord/bot.py", line 1130, in invoke_application_command
2|aiya     |     await ctx.command.invoke(ctx)
2|aiya     |   File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 376, in invoke
2|aiya     |     await injected(ctx)
2|aiya     |   File "/usr/local/lib/python3.10/dist-packages/discord/commands/core.py", line 139, in wrapped
2|aiya     |     raise ApplicationCommandInvokeError(exc) from exc
2|aiya     | discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

**Comment by wizz13150** [comment]
Hey,

same as your other issue. 
This 404 is due to a 'non-responding' webui, for some reason.
Does it happen from time to time, or systematically?

The usual cause for this is simply when running the webui on a very low-end computer.
Or to request the WebUI when being in a 'frozen' state, like when using Soft Inpainting (not a bot option, just a comment) or when clicking in the WebUI console, freezing the code.
Again, i don't think anyone experience this.

Hope you'll fix this.

Cheers ! 🥂
