### ISSUE TITLE
KeyError: 'dependencies'

### ISSUE THREAD

**Issue by bloodk1n** [Kilvoctu/aiyabot#9]
The latest commit mentioned the fix of this issue, but I am still able to recreate the error on a fresh clone.
Have tried issue #2 's fix by ironing out the crlf, still no luck. 
Any investigation is greatly appreciated!

```python
Ignoring exception in command draw:
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 970, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "C:\Users\\Desktop\aipaint\aiyabot\core\stablecog.py", line 141, in dream_handler
    PayloadFormatter.do_format(self, PayloadFormatter.PayloadFormat.TXT2IMG)
  File "C:\Users\\Desktop\aipaint\aiyabot\core\PayloadFormatter.py", line 54, in do_format
    dependenciesjson = responsestr["dependencies"]
KeyError: 'dependencies'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 1088, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 374, in invoke
    await injected(ctx)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'dependencies'
```

**Comment by Pyrotuna** [comment]
Please paste the rest of your log, it might be a error way back that traced to this

**Comment by bloodk1n** [comment]
> Please paste the rest of your log, it might be a error way back that traced to this

This is the rest of the error log. The error pops up right after the bot login message, sending /draw command directly causes this.

**Comment by Pyrotuna** [comment]
I meant, the full log, to get the full picture.

I recently got the same problem and it was an error in with the adapter called in the first lines but the bot kept running

**Comment by Pyrotuna** [comment]
Sorry, just realized it _could_ be too much info.

It's a blind shot, but try changing https to http in .env

**Comment by Kilvoctu** [comment]
Yeah, this is quite a tough issue. I've run into this issue occasionally in the past, and I can't find a concrete solution. Doesn't help that prior to this bot, I have no python experience lol.
I can recreate this issue now under certain conditions and will go through my investigation into the issue.

As you can see in the log, it's happening on this line: https://github.com/Kilvoctu/aiyabot/blob/fc9928cd8f84601d3aaf60503235b2f27c69a542/core/stablecog.py#L141 So this function is the first thing that happens right after /draw is executed. That's why the bot will run, but may break after using /draw.

What I thought was happening is that function do_format() in payloadformatter.py is trying run before the setup() initializes everything. setup() prints some stuff to the log, but it doesn't happen when the KeyError issue comes up.
My idea that I tried in https://github.com/Kilvoctu/aiyabot/commit/5b7c713766b753b2770a366db3b65816fa67e551 was move the line above earlier into the code. https://github.com/Kilvoctu/aiyabot/blob/5b7c713766b753b2770a366db3b65816fa67e551/core/stablecog.py#L57 This area is where the slash command is initialized. I also thought it made more sense to do the formatting here, rather than every single time /draw happens. Anyway, moving that line of code to this position recreates the KeyError for me.

My fix was basically *force* setup() to happen by dropping it directly into do_format().
https://github.com/Kilvoctu/aiyabot/blob/5b7c713766b753b2770a366db3b65816fa67e551/core/PayloadFormatter.py#L20 Maybe not the most elegant solution, but it worked for me when I tried it (it ends up doing setup() twice). It didn't work for the other user, though, so I'm not sure.

As a sidenote, I also can achieve the same "fix" for myself by putting 
`PayloadFormatter.setup()` right above `PayloadFormatter.do_format(self, PayloadFormatter.PayloadFormat.TXT2IMG)` in stablecog.py

**Comment by bloodk1n** [comment]
> Yeah, this is quite a tough issue. I've run into this issue occasionally in the past and can't find a concrete solution. Doesn't help that prior to this bot, I have no python experience lol, and I'm on Windows. I can recreate this issue now under certain conditions and will go through my investigation into it.

Thank you for the in-depth analyzation of the issue itself, Kilvoctu.
But unfortunately after applying all solution, cross comparison between them, the error persists in every scenario.
The error message is exactly the same except some changes to the column # due to added lines.
Further system info if this helps: Running on Python 3.10.6, Windows 11, and a Trad. Chinese system.
I have tried moving the entire repo to Ubuntu 22.04 server, interestly enough, it just refuses to run. Maybe the build is a tad bit different.

**Comment by Kilvoctu** [comment]
After consulting with a developer buddy of mine, I cleaned up my code to try to be compatible with other platforms.
Try pulling the latest commit and see if it's working for you.

I merged Pyrotuna's PR for autovenv with the launch.bat. You can use the bat file, or you can do the original way and run `python bot.py` like before.

**Comment by Kilvoctu** [comment]
I think I'll try to refactor the payload formatter and hopefully that will fix it.
It's puzzling since I don't get the issue for myself on fresh installs, and it was tested on both windows and linux. 🤔

**Comment by Kilvoctu** [comment]
Try pulling the latest commit and see if it's working now. 🤔
